site_name: tfgarden
site_author: Shakshi3104
site_description: Documentation of TensorFlow model Garden for HASC
repo_name: 'GitHub'
repo_url: https://github.com/Shakshi3104/tfgarden

nav:
    - Home: index.md
    - Installation: install.md
    - Quickstart: quickstart.md
    - Reference: reference.md

# plugins:
#     - search
#         lang:
#             - en
#             - ja

# readthedocs
# theme:
#   name: readthedocs
#   locale: en
#   highlightjs: true
#   include_sidebar: false

# material
theme:
    name: material
    language: ja

    # これ入れるとブラウザでエラーが出る
    # features:
    #     tabs: true

#extra_javascript:
#    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
#    - mdx_math
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences

    # Noteとか警告文とか
    - admonition

    # 注釈
    - footnotes

    # 絵文字
    - pymdownx.emoji

    # Webアイコンフォント(要インストール)
    # - fontawesome_markdown

# bootstrap4
# theme:
#     name: bootstrap4
#     suppress_nextprev: true

# cinder
# theme:
#     name: null
#     custom_dir: 'cinder-1.2.0/cinder'